version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8060:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - apache

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloudex
    volumes:
        - ./data:/var/lib/postgresql/data
        
  apache:
    image: php:8.1-apache
    ports:
      - "8060:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    command: ['apache2-foreground']
